#! /bin/zsh

TIMEFMT="%E"

t=10
n=10000

make

mkdir res

echo $n > res/input.txt

printf "\033[1mComparing execution time of programs generating random tree (n = $n): \n\033[0m"

for i in {1..$t}
do
	printf "\n"

	printf "Brute-force solution: [\033[32m"
	{ time bin/brute_force/generate_random_tree < res/input.txt > res/output.txt; } 2>&1 | tr -d '\n'
	printf "\033[0m]\n"

	printf "Prüfer code solution: [\033[32m"
	{ time bin/pruefer/generate_random_tree < res/input.txt > res/output.txt; } 2>&1 | tr -d '\n'
	printf "\033[0m]\n"
done
