#! /bin/zsh

TIMEFMT="%E"
make
mkdir res

t=1000
n=100000
m=100000

for i in {1..$t}
do
	printf "\033[1mTest case \033[1;96m$i\033[0m/\033[1;96m$t\033[0m\n" &&

	bin/random_test_data_generators/xenia_and_tree $n $m > res/input.txt &&

	printf "Depth-first search solution: \033[96m" &&
	{ time bin/brute_force/xenia_and_tree < res/input.txt > res/output_brutal.txt; } 2>&1 | tr -d '\n' &&
	printf "\033[0m\n" &&

	printf "Centroid decomposition solution: \033[96m"
	{ time bin/codeforces/xenia_and_tree < res/input.txt > res/output.txt; } 2>&1 | tr -d '\n' &&
	printf "\033[0m\n" &&

	cmp --silent res/output_brutal.txt res/output.txt &&
	printf "\033[1;92mSuccess!\033[0m\n\n" ||
	printf "\033[1;91mFailure!\033[0m\n\n"
done
