#! /bin/zsh

TIMEFMT="%E"

t=1000
n=100000

make

for i in {1..$t}
do
	printf "\033[1mTest case \033[1;96m$i\033[0m/\033[1;96m$t\033[0m\n" &&

	echo $n | bin/pruefer/generate_random_tree > res/input.txt &&

	printf "Model solution: \033[96m" &&
	{ time bin/model/encode < res/input.txt > res/output_module.txt; } 2>&1 | tr -d '\n' &&
	printf "\033[0m\n" &&

	printf "Present solution: \033[96m"
	{ time bin/pruefer/encode < res/input.txt > res/output_present.txt; } 2>&1 | tr -d '\n' &&
	printf "\033[0m\n"

	cmp --silent res/output_module.txt res/output_present.txt &&
	printf "\033[1;92mSuccess!\033[0m\n\n" ||
	printf "\033[1;91mFailure!\033[0m\n\n"
done
